version: '3'
services:
    webdriverio:
        build: .
        image: huli/webdriverio
        depends_on:
            - chrome
        volumes:
            - ./app:/app

    hub:
        image: selenium/hub
        ports:
            - 4444:4444

    chrome:
        image: selenium/node-chrome
        ports:
            - 5900
        environment:
            - HUB_PORT_4444_TCP_ADDR=hub
        depends_on:
            - hub